// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/mutezebra/subject-review/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.Cors()}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWT()}
}

func _updatenameMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWT()}
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWT()}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getverifycodeMw() []app.HandlerFunc {
	return nil
}

func _getpasswordverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuseravatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfooptionsMw() []app.HandlerFunc {
	// your code...
	return nil
}
