// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/mutezebra/subject-review/pkg/middleware"

	"github.com/mutezebra/subject-review/config"
	"github.com/mutezebra/subject-review/pkg/inject"
)

func main() {
	Init()

	h := server.Default(
		server.WithHostPorts("0.0.0.0:8888"))
	h.Use(middleware.Cors())
	h.Static("/assets/avatar", "")

	register(h)
	h.Spin()
}

func Init() {
	config.InitConfig()
	inject.UserInject()
	inject.SubjectInject()
}
