// Code generated by hertz generator.

package base

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/mutezebra/subject-review/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.Cors()}
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}
